### ISSUE TITLE
Needs a readme.

### ISSUE THREAD

**Issue by TechFounder** [MaddTheSane/perian#4]
Hi, it would be nice to have a read me included for this repo to let people know how to install this without a .dmg installer.  It would also be great if you can include in the readme the current known issues/bugs with the version. Thanks.

**Comment by Jeezy4** [comment]
You can find the DMG file : https://github.com/MaddTheSane/perian/releases
I agree on it for us to lists of changes in each version.

**Comment by TechFounder** [comment]
Sweet, thanks!

I'm running the last stable release version 1.2.3.  Do you recommend that I upgrade now or wait until a more stable release? I don't what's changed since 1.2.3?

**Comment by Jeezy4** [comment]
The current version is 1.3.1 on Github is stable.
The only change is that he announced: "This release uses the latest release of FFMpeg."

**Comment by jelias** [comment]
We could write the readme for MaddTheSane... He is doing a lot keeping Perian working, you know what you want, why not make it yourself and then share it with MaddTheSane? Don't forget to use [Markdown](https://help.github.com/articles/github-flavored-markdown)!
