### ISSUE TITLE
AC-3 decoder stil broken on 10.8 and later

### ISSUE THREAD

**Issue by galad87** [MaddTheSane/perian#5]
The a52codec components does not work on 10.8 and later because it forbids the writing of kAudioCodecPropertyOutputChannelLayout property. Core Audio on ML want to set it, and if it can't it fails.

The responsible code start at line 333 of ACShepA52Decoder.cpp .

**Comment by MaddTheSane** [comment]
Please note that the a52codec is in it's own repository here: https://github.com/MaddTheSane/a52codec
Please post a bug report there, as well as adding a comment to the affected file and line.
